### ISSUE TITLE
Check with Stanbic about payments to order equipment abroad

### ISSUE THREAD

**Issue by innocentmaholi** [Openskiesfellows/Project-Management#19]

**Comment by ivangayton** [comment]
There are probably a few questions we could ask Stanbic:

# Open (general) questions
- How can we pay for stuff from overseas suppliers? Most require a credit card number. 
- How do your other institutional customers buy or pay for things outside of Tanzania?

# Closed (specific) questions
- Can we send a wire transfer to an overseas account?
  - To a personal account?
  - To a corporate account?
  - How much are the fees?
  - Does Stanbic have some particular policy about withholding taxes or other deductions when sending wire transfers?
