### ISSUE TITLE
Get containers for organization

### ISSUE THREAD

**Issue by evilGmonkey** [Openskiesfellows/Project-Management#26]
Need to have containers for organization, please can you check town and game and get.

**Comment by dignah** [comment]
From town 

- Plastic drawer storage depending on the size
 Big size 260000tsh
 Medium size 250000tsh
 Storage boxes 
- Different kind of containers 

From Game
-Plastic drawer small size 51720tsh
-Different kind of small containers

From Shoppers
Plastic drawer big size 250000tsh
Plastic drawer medium size 160000tsh
Round container 25000tsh

**Comment by evilGmonkey** [comment]
no action for me
